### ISSUE TITLE
Continue monitoring once finished processing files/folders

### ISSUE THREAD

**Issue by TonyBrobston** [ehendrix23/tesla_dashcam#125]
First off, thank you to everyone that has contributed to this project. I'm really glad this exists, it's awesome.

I'm running the equivalent of: 

`tesla_dashcam --swap --rear --layout DIAMOND --quality HIGH --fps 33 --compression ultrafast /root/Import`

When the files/folders in `/root/Import` are finished being processed the process ends, but I'd like it to continue waiting for new files/folders to process. Because of my setup files will sporadically show up in `/root/Import` and I would like `tesla_dashcam` to begin processing the files again as they show up. Is this possible?

**Comment by TonyBrobston** [comment]
This is additional information that may be more information than needed.

I'm using [teslausb](https://github.com/marcone/teslausb), plex, samba, and tesla_dashcam. teslausb runs on a Raspberry Pi and acts as a usb flash drive in my Tesla Model 3, when the Raspberry Pi is connected to wifi it transfers the Tesla Dashcam footage to a samba share, this footage is then processed by tesla_dashcam, and then that processed footage is dropped in a folder that plex is looking at.

Here's the `docker-compose.yml` that makes all this happen:

```
version: '3'

services:
  plex:
    image: linuxserver/plex
    restart: unless-stopped
    network_mode: host
    volumes:
    - ~/plex/config:/config
    - /RAID:/data/raid
    environment:
      VERSION: latest 
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago

  samba:
    image: dperson/samba
    restart: unless-stopped
    ports:
    - 139:139
    - 445:445
    volumes:
    - /RAID/Samba:/mount
    env_file:
    - .env
    read_only: true
    tmpfs:
    - /tmp
    stdin_open: true
    tty: true
    command: '-s "Mount;/mount;yes;no;no;$USERNAME" -u "$USERNAME;$PASSWORD"'

  tesla_dashcam:
    image: magicalyak/tesla_dashcam
    environment:
      TZ: America/Chicago
    volumes:
    - /RAID/Samba:/root/Import
    - /RAID/Output:/root/Videos/Tesla_Dashcam
    command: '--swap --rear --layout DIAMOND --quality HIGH --fps 33 --compression ultrafast /root/Import'

  tautulli:
    image: linuxserver/tautulli
    restart: unless-stopped
    volumes:
    - ~/tautulli/config:/config
    - ~/tautulli/logs:/logs:ro
    ports:
    - 8181:8181
    environment:
      VERSION: latest
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
```
