### ISSUE TITLE
Issue using Dockerfile

### ISSUE THREAD

**Issue by TonyBrobston** [ehendrix23/tesla_dashcam#205]
Maybe @magicalyak can help weigh in.

I was previously using your docker image from docker hub, I tried swapping to the Dockerfile in this repo, any pointers on what I'm doing wrong here?

I have this repo cloned two directories up.

```
services:
  tesla_dashcam:
    #image: magicalyak/tesla_dashcam
    context:
        dockerfile: ../../tesla_dashcam/Dockerfile
    restart: unless-stopped
    environment:
    - TZ=America/Chicago
    volumes:
    - /RAID/Input:/root/Import
    - /RAID/Output:/root/Videos/Tesla_Dashcam
    command: '--swap --rear --delete_source --layout DIAMOND --quality HIGH --fps 33 --gpu_type nvidia --compression veryslow /root/Import'
```

When I run a `docker compose up` I get:
```
tesla_dashcam-1  \| python3: can't open file '//tesla_dashcam/tesla_dashcam.py': [Errno 2] No such file or directory                    tesla_dashcam-1 exited with code 0
```
